# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import test_pb2 as test__pb2


class TestStub(object):
  """测试hello的协议
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.hello = channel.unary_unary(
        '/test.Test/hello',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=test__pb2.TestReply.FromString,
        )


class TestServicer(object):
  """测试hello的协议
  """

  def hello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TestServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'hello': grpc.unary_unary_rpc_method_handler(
          servicer.hello,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=test__pb2.TestReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'test.Test', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
