<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dubbo/test.proto

namespace GPBMetadata\Dubbo;

class Test
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        \GPBMetadata\Dao::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aaf030a10647562626f2f746573742e70726f746f120e636f6d2e746573" .
            "742e647562626f1a1e676f6f676c652f70726f746f6275662f7772617070" .
            "6572732e70726f746f1a0964616f2e70726f746f221c0a09546573745265" .
            "706c79120f0a076d65737361676518012001280932b9020a045465737412" .
            "3c0a0568656c6c6f12162e676f6f676c652e70726f746f6275662e456d70" .
            "74791a192e636f6d2e746573742e647562626f2e546573745265706c7922" .
            "0012380a056563686f6f121c2e676f6f676c652e70726f746f6275662e53" .
            "7472696e6756616c75651a0f2e636f6d2e746573742e4563686f6f220012" .
            "340a066563686f6f7312162e676f6f676c652e70726f746f6275662e456d" .
            "7074791a102e636f6d2e746573742e4563686f6f73220012440a0b636c65" .
            "61725f6563686f6f12162e676f6f676c652e70726f746f6275662e456d70" .
            "74791a1b2e676f6f676c652e70726f746f6275662e496e74333256616c75" .
            "652200123d0a0c7570646174655f6563686f6f120f2e636f6d2e74657374" .
            "2e4563686f6f1a1a2e676f6f676c652e70726f746f6275662e426f6f6c56" .
            "616c75652200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

