# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import dao_pb2 as dao__pb2
from dubbo import test_pb2 as dubbo_dot_test__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


class TestStub(object):
  """测试hello的协议
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.hello = channel.unary_unary(
        '/com.test.dubbo.Test/hello',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=dubbo_dot_test__pb2.TestReply.FromString,
        )
    self.echoo = channel.unary_unary(
        '/com.test.dubbo.Test/echoo',
        request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
        response_deserializer=dao__pb2.Echoo.FromString,
        )


class TestServicer(object):
  """测试hello的协议
  """

  def hello(self, request, context):
    """返回欢迎
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def echoo(self, request, context):
    """测试数据库
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TestServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'hello': grpc.unary_unary_rpc_method_handler(
          servicer.hello,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=dubbo_dot_test__pb2.TestReply.SerializeToString,
      ),
      'echoo': grpc.unary_unary_rpc_method_handler(
          servicer.echoo,
          request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
          response_serializer=dao__pb2.Echoo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.test.dubbo.Test', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
