<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dao.proto

namespace Com\Test;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.test.Echoos</code>
 */
class Echoos extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .com.test.Echoo item = 1;</code>
     */
    private $item;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Com\Test\Echoo[]|\Google\Protobuf\Internal\RepeatedField $item
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dao::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .com.test.Echoo item = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItem()
    {
        return $this->item;
    }

    /**
     * Generated from protobuf field <code>repeated .com.test.Echoo item = 1;</code>
     * @param \Com\Test\Echoo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItem($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Com\Test\Echoo::class);
        $this->item = $arr;

        return $this;
    }

}

