# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dubbo/test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import dao_pb2 as dao__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dubbo/test.proto',
  package='com.test.dubbo',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x64ubbo/test.proto\x12\x0e\x63om.test.dubbo\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\tdao.proto\"\x1c\n\x0bReqTestEcho\x12\r\n\x05input\x18\x01 \x01(\t\"\x1d\n\x0bRspTestEcho\x12\x0e\n\x06output\x18\x01 \x01(\t\"\x1c\n\tTestReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb6\x03\n\x04Test\x12<\n\x05hello\x12\x16.google.protobuf.Empty\x1a\x19.com.test.dubbo.TestReply\"\x00\x12\x42\n\x04\x65\x63ho\x12\x1b.com.test.dubbo.ReqTestEcho\x1a\x1b.com.test.dubbo.RspTestEcho\"\x00\x12\x38\n\x05\x65\x63hoo\x12\x1c.google.protobuf.StringValue\x1a\x0f.com.test.Echoo\"\x00\x12\x34\n\x06\x65\x63hoos\x12\x16.google.protobuf.Empty\x1a\x10.com.test.Echoos\"\x00\x12\x43\n\nechooclear\x12\x16.google.protobuf.Empty\x1a\x1b.google.protobuf.Int32Value\"\x00\x12<\n\x0b\x65\x63hooupdate\x12\x0f.com.test.Echoo\x1a\x1a.google.protobuf.BoolValue\"\x00\x12\x39\n\x05\x65rror\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x32K\n\x05Test1\x12\x42\n\x04\x65\x63ho\x12\x1b.com.test.dubbo.ReqTestEcho\x1a\x1b.com.test.dubbo.RspTestEcho\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,dao__pb2.DESCRIPTOR,])




_REQTESTECHO = _descriptor.Descriptor(
  name='ReqTestEcho',
  full_name='com.test.dubbo.ReqTestEcho',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='com.test.dubbo.ReqTestEcho.input', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=136,
)


_RSPTESTECHO = _descriptor.Descriptor(
  name='RspTestEcho',
  full_name='com.test.dubbo.RspTestEcho',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='output', full_name='com.test.dubbo.RspTestEcho.output', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=167,
)


_TESTREPLY = _descriptor.Descriptor(
  name='TestReply',
  full_name='com.test.dubbo.TestReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='com.test.dubbo.TestReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=197,
)

DESCRIPTOR.message_types_by_name['ReqTestEcho'] = _REQTESTECHO
DESCRIPTOR.message_types_by_name['RspTestEcho'] = _RSPTESTECHO
DESCRIPTOR.message_types_by_name['TestReply'] = _TESTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqTestEcho = _reflection.GeneratedProtocolMessageType('ReqTestEcho', (_message.Message,), {
  'DESCRIPTOR' : _REQTESTECHO,
  '__module__' : 'dubbo.test_pb2'
  # @@protoc_insertion_point(class_scope:com.test.dubbo.ReqTestEcho)
  })
_sym_db.RegisterMessage(ReqTestEcho)

RspTestEcho = _reflection.GeneratedProtocolMessageType('RspTestEcho', (_message.Message,), {
  'DESCRIPTOR' : _RSPTESTECHO,
  '__module__' : 'dubbo.test_pb2'
  # @@protoc_insertion_point(class_scope:com.test.dubbo.RspTestEcho)
  })
_sym_db.RegisterMessage(RspTestEcho)

TestReply = _reflection.GeneratedProtocolMessageType('TestReply', (_message.Message,), {
  'DESCRIPTOR' : _TESTREPLY,
  '__module__' : 'dubbo.test_pb2'
  # @@protoc_insertion_point(class_scope:com.test.dubbo.TestReply)
  })
_sym_db.RegisterMessage(TestReply)



_TEST = _descriptor.ServiceDescriptor(
  name='Test',
  full_name='com.test.dubbo.Test',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=200,
  serialized_end=638,
  methods=[
  _descriptor.MethodDescriptor(
    name='hello',
    full_name='com.test.dubbo.Test.hello',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_TESTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='echo',
    full_name='com.test.dubbo.Test.echo',
    index=1,
    containing_service=None,
    input_type=_REQTESTECHO,
    output_type=_RSPTESTECHO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='echoo',
    full_name='com.test.dubbo.Test.echoo',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE,
    output_type=dao__pb2._ECHOO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='echoos',
    full_name='com.test.dubbo.Test.echoos',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=dao__pb2._ECHOOS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='echooclear',
    full_name='com.test.dubbo.Test.echooclear',
    index=4,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_wrappers__pb2._INT32VALUE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='echooupdate',
    full_name='com.test.dubbo.Test.echooupdate',
    index=5,
    containing_service=None,
    input_type=dao__pb2._ECHOO,
    output_type=google_dot_protobuf_dot_wrappers__pb2._BOOLVALUE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='error',
    full_name='com.test.dubbo.Test.error',
    index=6,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEST)

DESCRIPTOR.services_by_name['Test'] = _TEST


_TEST1 = _descriptor.ServiceDescriptor(
  name='Test1',
  full_name='com.test.dubbo.Test1',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=640,
  serialized_end=715,
  methods=[
  _descriptor.MethodDescriptor(
    name='echo',
    full_name='com.test.dubbo.Test1.echo',
    index=0,
    containing_service=None,
    input_type=_REQTESTECHO,
    output_type=_RSPTESTECHO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEST1)

DESCRIPTOR.services_by_name['Test1'] = _TEST1

# @@protoc_insertion_point(module_scope)
