<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dao.proto

namespace GPBMetadata;

class Dao
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a7a0a0964616f2e70726f746f1208636f6d2e7465737422320a05456368" .
            "6f6f120a0a026964180120012805120d0a05696e70757418022001280912" .
            "0e0a066f757470757418032001280922270a064563686f6f73121d0a0469" .
            "74656d18012003280b320f2e636f6d2e746573742e4563686f6f62067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

