<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dao.proto

namespace GPBMetadata;

class Dao
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
z
	dao.protocom.test"2
Echoo

id (
input (	
output (	"\'
Echoos
item (2.com.test.Echoobproto3'
        , true);

        static::$is_initialized = true;
    }
}

